# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZXvRn0Y65ogcy6dSS7h21MEHLy3Ja0b
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression  # Or any other model
import pickle

data = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

# ... data preprocessing (if needed)

X = data[['Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps', 'Sleep Disorder']]  # Select features
y = data['Heart Rate']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()  # Choose a model
model.fit(X_train, y_train)

# Save the model
with open('trained_model.pkl', 'wb') as file:
    pickle.dump(model, file)